version: '3'

services:
  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./services/nginx/devops.lovata.tech.conf:/bitnami/nginx/conf/vhosts/devops.lovata.tech.conf"
    depends_on:
      - app
  app:
    image: 'bitnami/php-fpm:latest'
    volumes:
      - "./services/app:/app"
